PUT http://localhost:3003/api/blogs/64954afcaa2ae33d5b76046e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1ybW9uZ28iLCJpZCI6IjY0OTU0OTFiNmQwOTFlZGQ2YWJjMzc2YSIsImlhdCI6MTY4Nzk4NjkzNywiZXhwIjoxNjg3OTg4NzM3fQ.RXqFGbxW_3V3iU3Z_yBax3ZeZS69j0-WuPaNtkIWg_k

{
"title": "Post title",
"author": "Mr. Dijsktra",
"url": "https://example.com",
"likes": "1000",
"userId": "6495491b6d091edd6abc376a"
}